spring:
  profiles:
    active: prd
--- # dev
spring:
  profiles: dev
server:
  port: 9090

--- # test
spring:
  profiles: test
server:
  port: 9091

--- # uat
spring:
  profiles: uat
server:
  port: 9092

--- # prd
spring:
  profiles: prd
server:
  port: 9093